-- SupplyGraph AI: Curated Views
-- Zero-copy views over SNOWFLAKE_SAMPLE_DATA.TPCH_SF1

-- Regions: Nation-region mapping
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_REGIONS AS
SELECT
    R.R_REGIONKEY AS REGION_KEY, R.R_NAME AS REGION_NAME,
    N.N_NATIONKEY AS NATION_KEY, N.N_NAME AS NATION_NAME
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N ON R.R_REGIONKEY = N.N_REGIONKEY;

-- Suppliers: Vendor master data
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_SUPPLIERS AS
SELECT
    S.S_SUPPKEY AS SUPPLIER_KEY, S.S_NAME AS SUPPLIER_NAME,
    S.S_ADDRESS AS SUPPLIER_ADDRESS, S.S_PHONE AS SUPPLIER_PHONE,
    S.S_ACCTBAL AS ACCOUNT_BALANCE,
    N.N_NAME AS NATION_NAME, R.R_NAME AS REGION_NAME,
    N.N_NATIONKEY AS NATION_KEY, R.R_REGIONKEY AS REGION_KEY
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER S
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY;

-- Parts: Product catalog
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_PARTS AS
SELECT
    P.P_PARTKEY AS PART_KEY, P.P_NAME AS PART_NAME,
    P.P_MFGR AS MANUFACTURER, P.P_BRAND AS BRAND,
    P.P_TYPE AS PART_TYPE, P.P_SIZE AS PART_SIZE,
    P.P_CONTAINER AS CONTAINER_TYPE, P.P_RETAILPRICE AS RETAIL_PRICE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART P;

-- Customers: Buyer master data
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_CUSTOMERS AS
SELECT
    C.C_CUSTKEY AS CUSTOMER_KEY, C.C_NAME AS CUSTOMER_NAME,
    C.C_ADDRESS AS CUSTOMER_ADDRESS, C.C_PHONE AS CUSTOMER_PHONE,
    C.C_ACCTBAL AS ACCOUNT_BALANCE, C.C_MKTSEGMENT AS MARKET_SEGMENT,
    N.N_NAME AS NATION_NAME, R.R_NAME AS REGION_NAME,
    N.N_NATIONKEY AS NATION_KEY, R.R_REGIONKEY AS REGION_KEY
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY;

-- Supplier-Part: Catalog with availability, cost, margin
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_SUPPLIER_PARTS AS
SELECT
    PS.PS_PARTKEY AS PART_KEY, PS.PS_SUPPKEY AS SUPPLIER_KEY,
    PS.PS_AVAILQTY AS AVAILABLE_QUANTITY, PS.PS_SUPPLYCOST AS SUPPLY_COST,
    P.P_NAME AS PART_NAME, P.P_BRAND AS BRAND, P.P_TYPE AS PART_TYPE,
    P.P_RETAILPRICE AS RETAIL_PRICE,
    S.S_NAME AS SUPPLIER_NAME, N.N_NAME AS SUPPLIER_NATION, R.R_NAME AS SUPPLIER_REGION,
    PS.PS_AVAILQTY * PS.PS_SUPPLYCOST AS INVENTORY_VALUE,
    CASE WHEN PS.PS_SUPPLYCOST > 0
         THEN ROUND((P.P_RETAILPRICE - PS.PS_SUPPLYCOST) / PS.PS_SUPPLYCOST * 100, 2)
         ELSE NULL END AS MARGIN_PERCENTAGE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP PS
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART P ON PS.PS_PARTKEY = P.P_PARTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER S ON PS.PS_SUPPKEY = S.S_SUPPKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY;

-- Orders: Purchase orders with time dimensions
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_ORDERS AS
SELECT
    O.O_ORDERKEY AS ORDER_KEY, O.O_CUSTKEY AS CUSTOMER_KEY,
    O.O_ORDERSTATUS AS ORDER_STATUS, O.O_TOTALPRICE AS TOTAL_PRICE,
    O.O_ORDERDATE AS ORDER_DATE, O.O_ORDERPRIORITY AS ORDER_PRIORITY,
    O.O_CLERK AS ORDER_CLERK,
    C.C_NAME AS CUSTOMER_NAME, C.C_MKTSEGMENT AS MARKET_SEGMENT,
    N.N_NAME AS CUSTOMER_NATION, R.R_NAME AS CUSTOMER_REGION,
    YEAR(O.O_ORDERDATE) AS ORDER_YEAR,
    QUARTER(O.O_ORDERDATE) AS ORDER_QUARTER,
    TO_CHAR(O.O_ORDERDATE, 'YYYY-MM') AS ORDER_MONTH
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY;

-- Shipments: Central fact table with delivery metrics
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_SHIPMENTS AS
SELECT
    L.L_ORDERKEY AS ORDER_KEY, L.L_LINENUMBER AS LINE_NUMBER,
    L.L_PARTKEY AS PART_KEY, L.L_SUPPKEY AS SUPPLIER_KEY,
    L.L_QUANTITY AS QUANTITY, L.L_EXTENDEDPRICE AS EXTENDED_PRICE,
    L.L_DISCOUNT AS DISCOUNT, L.L_TAX AS TAX,
    L.L_RETURNFLAG AS RETURN_FLAG, L.L_LINESTATUS AS LINE_STATUS,
    L.L_SHIPDATE AS SHIP_DATE, L.L_COMMITDATE AS COMMIT_DATE,
    L.L_RECEIPTDATE AS RECEIPT_DATE,
    L.L_SHIPINSTRUCT AS SHIP_INSTRUCTION, L.L_SHIPMODE AS SHIP_MODE,
    O.O_ORDERDATE AS ORDER_DATE, O.O_ORDERPRIORITY AS ORDER_PRIORITY,
    ROUND(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT), 2) AS NET_REVENUE,
    ROUND(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT) * (1 + L.L_TAX), 2) AS GROSS_REVENUE,
    DATEDIFF('day', O.O_ORDERDATE, L.L_RECEIPTDATE) AS DELIVERY_LEAD_TIME_DAYS,
    DATEDIFF('day', L.L_SHIPDATE, L.L_RECEIPTDATE) AS SHIPPING_LEAD_TIME_DAYS,
    DATEDIFF('day', O.O_ORDERDATE, L.L_SHIPDATE) AS PROCESSING_TIME_DAYS,
    CASE WHEN L.L_RECEIPTDATE <= L.L_COMMITDATE THEN 1 ELSE 0 END AS IS_ON_TIME,
    CASE WHEN L.L_RECEIPTDATE > L.L_COMMITDATE THEN 1 ELSE 0 END AS IS_LATE,
    GREATEST(DATEDIFF('day', L.L_COMMITDATE, L.L_RECEIPTDATE), 0) AS DAYS_LATE,
    CASE L.L_RETURNFLAG WHEN 'R' THEN 'Returned' WHEN 'A' THEN 'Accepted' WHEN 'N' THEN 'None' ELSE L.L_RETURNFLAG END AS RETURN_STATUS,
    S.S_NAME AS SUPPLIER_NAME, SN.N_NAME AS SUPPLIER_NATION, SR.R_NAME AS SUPPLIER_REGION,
    C.C_NAME AS CUSTOMER_NAME, C.C_MKTSEGMENT AS MARKET_SEGMENT,
    CN.N_NAME AS CUSTOMER_NATION, CR.R_NAME AS CUSTOMER_REGION,
    P.P_NAME AS PART_NAME, P.P_BRAND AS BRAND, P.P_TYPE AS PART_TYPE,
    YEAR(O.O_ORDERDATE) AS ORDER_YEAR,
    QUARTER(O.O_ORDERDATE) AS ORDER_QUARTER,
    TO_CHAR(O.O_ORDERDATE, 'YYYY-MM') AS ORDER_MONTH
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM L
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER S ON L.L_SUPPKEY = S.S_SUPPKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION SN ON S.S_NATIONKEY = SN.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION SR ON SN.N_REGIONKEY = SR.R_REGIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION CN ON C.C_NATIONKEY = CN.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION CR ON CN.N_REGIONKEY = CR.R_REGIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART P ON L.L_PARTKEY = P.P_PARTKEY;

-- Supplier Performance: Pre-aggregated scorecard
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_SUPPLIER_PERFORMANCE AS
SELECT
    S.S_SUPPKEY AS SUPPLIER_KEY, S.S_NAME AS SUPPLIER_NAME,
    N.N_NAME AS SUPPLIER_NATION, R.R_NAME AS SUPPLIER_REGION,
    COUNT(DISTINCT L.L_ORDERKEY) AS TOTAL_ORDERS,
    COUNT(*) AS TOTAL_LINE_ITEMS,
    SUM(L.L_QUANTITY) AS TOTAL_QUANTITY_SHIPPED,
    ROUND(SUM(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT)), 2) AS TOTAL_REVENUE,
    ROUND(AVG(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT)), 2) AS AVG_LINE_REVENUE,
    SUM(CASE WHEN L.L_RECEIPTDATE <= L.L_COMMITDATE THEN 1 ELSE 0 END) AS ON_TIME_COUNT,
    SUM(CASE WHEN L.L_RECEIPTDATE > L.L_COMMITDATE THEN 1 ELSE 0 END) AS LATE_COUNT,
    ROUND(SUM(CASE WHEN L.L_RECEIPTDATE <= L.L_COMMITDATE THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS ON_TIME_DELIVERY_PCT,
    SUM(CASE WHEN L.L_RETURNFLAG != 'R' THEN 1 ELSE 0 END) AS FULFILLED_COUNT,
    ROUND(SUM(CASE WHEN L.L_RETURNFLAG != 'R' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS FILL_RATE_PCT,
    ROUND(AVG(DATEDIFF('day', O.O_ORDERDATE, L.L_RECEIPTDATE)), 1) AS AVG_DELIVERY_LEAD_TIME_DAYS,
    ROUND(AVG(DATEDIFF('day', L.L_SHIPDATE, L.L_RECEIPTDATE)), 1) AS AVG_SHIPPING_LEAD_TIME_DAYS,
    ROUND(AVG(DATEDIFF('day', O.O_ORDERDATE, L.L_SHIPDATE)), 1) AS AVG_PROCESSING_TIME_DAYS,
    ROUND(AVG(GREATEST(DATEDIFF('day', L.L_COMMITDATE, L.L_RECEIPTDATE), 0)), 1) AS AVG_DAYS_LATE,
    SUM(CASE WHEN L.L_RETURNFLAG = 'R' THEN 1 ELSE 0 END) AS RETURN_COUNT,
    ROUND(SUM(CASE WHEN L.L_RETURNFLAG = 'R' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS RETURN_RATE_PCT,
    ROUND(
        (SUM(CASE WHEN L.L_RECEIPTDATE <= L.L_COMMITDATE THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)) * 0.40
      + (SUM(CASE WHEN L.L_RETURNFLAG != 'R' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)) * 0.35
      + (100 - SUM(CASE WHEN L.L_RETURNFLAG = 'R' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)) * 0.25
    , 2) AS SUPPLIER_PERFORMANCE_SCORE,
    COUNT(DISTINCT L.L_PARTKEY) AS DISTINCT_PARTS_SUPPLIED,
    COUNT(DISTINCT O.O_CUSTKEY) AS DISTINCT_CUSTOMERS_SERVED
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER S
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM L ON S.S_SUPPKEY = L.L_SUPPKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
GROUP BY S.S_SUPPKEY, S.S_NAME, N.N_NAME, R.R_NAME;
