-- SupplyGraph AI: Curated Views
-- Zero-copy views over SNOWFLAKE_SAMPLE_DATA.TPCH_SF1 (original TPC-H data).
-- Columns marked [SYNTHETIC] come from the SYN_ enrichment tables in 02_synthetic_reference_data.sql.
-- Plant assignment rule [SYNTHETIC]: PLANT_KEY = MOD(PART_KEY, 10) + 1.

-- Regions: Nation-region mapping
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_REGIONS AS
SELECT
    R.R_REGIONKEY AS REGION_KEY, R.R_NAME AS REGION_NAME,
    N.N_NATIONKEY AS NATION_KEY, N.N_NAME AS NATION_NAME
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N ON R.R_REGIONKEY = N.N_REGIONKEY;

-- Suppliers: Vendor master data
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_SUPPLIERS AS
SELECT
    S.S_SUPPKEY AS SUPPLIER_KEY, S.S_NAME AS SUPPLIER_NAME,
    S.S_ADDRESS AS SUPPLIER_ADDRESS, S.S_PHONE AS SUPPLIER_PHONE,
    S.S_ACCTBAL AS ACCOUNT_BALANCE,
    N.N_NAME AS NATION_NAME, R.R_NAME AS REGION_NAME,
    N.N_NATIONKEY AS NATION_KEY, R.R_REGIONKEY AS REGION_KEY
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER S
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY;

-- Parts: Product catalog
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_PARTS AS
SELECT
    P.P_PARTKEY AS PART_KEY, P.P_NAME AS PART_NAME,
    P.P_MFGR AS MANUFACTURER, P.P_BRAND AS BRAND,
    P.P_TYPE AS PART_TYPE, P.P_SIZE AS PART_SIZE,
    P.P_CONTAINER AS CONTAINER_TYPE, P.P_RETAILPRICE AS RETAIL_PRICE,
    PL.PLANT_KEY, PL.PLANT_NAME, PL.PLANT_REGION                       -- [SYNTHETIC]
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART P
LEFT JOIN SUPPLYGRAPH_AI.SUPPLY_CHAIN.SYN_PLANTS PL ON PL.PLANT_KEY = MOD(P.P_PARTKEY, 10) + 1;

-- Customers: Buyer master data
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_CUSTOMERS AS
SELECT
    C.C_CUSTKEY AS CUSTOMER_KEY, C.C_NAME AS CUSTOMER_NAME,
    C.C_ADDRESS AS CUSTOMER_ADDRESS, C.C_PHONE AS CUSTOMER_PHONE,
    C.C_ACCTBAL AS ACCOUNT_BALANCE, C.C_MKTSEGMENT AS MARKET_SEGMENT,
    N.N_NAME AS NATION_NAME, R.R_NAME AS REGION_NAME,
    N.N_NATIONKEY AS NATION_KEY, R.R_REGIONKEY AS REGION_KEY
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY;

-- Supplier-Part: Catalog with availability, cost, margin
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_SUPPLIER_PARTS AS
SELECT
    PS.PS_PARTKEY AS PART_KEY, PS.PS_SUPPKEY AS SUPPLIER_KEY,
    PS.PS_AVAILQTY AS AVAILABLE_QUANTITY, PS.PS_SUPPLYCOST AS SUPPLY_COST,
    P.P_NAME AS PART_NAME, P.P_BRAND AS BRAND, P.P_TYPE AS PART_TYPE,
    P.P_RETAILPRICE AS RETAIL_PRICE,
    S.S_NAME AS SUPPLIER_NAME, N.N_NAME AS SUPPLIER_NATION, R.R_NAME AS SUPPLIER_REGION,
    PS.PS_AVAILQTY * PS.PS_SUPPLYCOST AS INVENTORY_VALUE,
    CASE WHEN PS.PS_SUPPLYCOST > 0
         THEN ROUND((P.P_RETAILPRICE - PS.PS_SUPPLYCOST) / PS.PS_SUPPLYCOST * 100, 2)
         ELSE NULL END AS MARGIN_PERCENTAGE,
    PL.PLANT_KEY, PL.PLANT_NAME, PL.PLANT_REGION                       -- [SYNTHETIC]
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP PS
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART P ON PS.PS_PARTKEY = P.P_PARTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER S ON PS.PS_SUPPKEY = S.S_SUPPKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY
LEFT JOIN SUPPLYGRAPH_AI.SUPPLY_CHAIN.SYN_PLANTS PL ON PL.PLANT_KEY = MOD(PS.PS_PARTKEY, 10) + 1;

-- Orders: Purchase orders with time dimensions
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_ORDERS AS
SELECT
    O.O_ORDERKEY AS ORDER_KEY, O.O_CUSTKEY AS CUSTOMER_KEY,
    O.O_ORDERSTATUS AS ORDER_STATUS, O.O_TOTALPRICE AS TOTAL_PRICE,
    O.O_ORDERDATE AS ORDER_DATE, O.O_ORDERPRIORITY AS ORDER_PRIORITY,
    O.O_CLERK AS ORDER_CLERK,
    C.C_NAME AS CUSTOMER_NAME, C.C_MKTSEGMENT AS MARKET_SEGMENT,
    N.N_NAME AS CUSTOMER_NATION, R.R_NAME AS CUSTOMER_REGION,
    YEAR(O.O_ORDERDATE) AS ORDER_YEAR,
    QUARTER(O.O_ORDERDATE) AS ORDER_QUARTER,
    TO_CHAR(O.O_ORDERDATE, 'YYYY-MM') AS ORDER_MONTH
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N ON C.C_NATIONKEY = N.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY;

-- Shipments: Central fact table with delivery metrics
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_SHIPMENTS AS
SELECT
    L.L_ORDERKEY AS ORDER_KEY, L.L_LINENUMBER AS LINE_NUMBER,
    L.L_PARTKEY AS PART_KEY, L.L_SUPPKEY AS SUPPLIER_KEY,
    L.L_QUANTITY AS QUANTITY, L.L_EXTENDEDPRICE AS EXTENDED_PRICE,
    L.L_DISCOUNT AS DISCOUNT, L.L_TAX AS TAX,
    L.L_RETURNFLAG AS RETURN_FLAG, L.L_LINESTATUS AS LINE_STATUS,
    L.L_SHIPDATE AS SHIP_DATE, L.L_COMMITDATE AS COMMIT_DATE,
    L.L_RECEIPTDATE AS RECEIPT_DATE,
    L.L_SHIPINSTRUCT AS SHIP_INSTRUCTION, L.L_SHIPMODE AS SHIP_MODE,
    O.O_ORDERDATE AS ORDER_DATE, O.O_ORDERPRIORITY AS ORDER_PRIORITY,
    ROUND(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT), 2) AS NET_REVENUE,
    ROUND(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT) * (1 + L.L_TAX), 2) AS GROSS_REVENUE,
    DATEDIFF('day', O.O_ORDERDATE, L.L_RECEIPTDATE) AS DELIVERY_LEAD_TIME_DAYS,
    DATEDIFF('day', L.L_SHIPDATE, L.L_RECEIPTDATE) AS SHIPPING_LEAD_TIME_DAYS,
    DATEDIFF('day', O.O_ORDERDATE, L.L_SHIPDATE) AS PROCESSING_TIME_DAYS,
    CASE WHEN L.L_RECEIPTDATE <= L.L_COMMITDATE THEN 1 ELSE 0 END AS IS_ON_TIME,
    CASE WHEN L.L_RECEIPTDATE > L.L_COMMITDATE THEN 1 ELSE 0 END AS IS_LATE,
    GREATEST(DATEDIFF('day', L.L_COMMITDATE, L.L_RECEIPTDATE), 0) AS DAYS_LATE,
    CASE L.L_RETURNFLAG WHEN 'R' THEN 'Returned' WHEN 'A' THEN 'Accepted' WHEN 'N' THEN 'None' ELSE L.L_RETURNFLAG END AS RETURN_STATUS,
    S.S_NAME AS SUPPLIER_NAME, SN.N_NAME AS SUPPLIER_NATION, SR.R_NAME AS SUPPLIER_REGION,
    C.C_NAME AS CUSTOMER_NAME, C.C_MKTSEGMENT AS MARKET_SEGMENT,
    CN.N_NAME AS CUSTOMER_NATION, CR.R_NAME AS CUSTOMER_REGION,
    P.P_NAME AS PART_NAME, P.P_BRAND AS BRAND, P.P_TYPE AS PART_TYPE,
    YEAR(O.O_ORDERDATE) AS ORDER_YEAR,
    QUARTER(O.O_ORDERDATE) AS ORDER_QUARTER,
    TO_CHAR(O.O_ORDERDATE, 'YYYY-MM') AS ORDER_MONTH,
    PL.PLANT_KEY, PL.PLANT_NAME, PL.PLANT_REGION                       -- [SYNTHETIC]
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM L
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER S ON L.L_SUPPKEY = S.S_SUPPKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION SN ON S.S_NATIONKEY = SN.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION SR ON SN.N_REGIONKEY = SR.R_REGIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER C ON O.O_CUSTKEY = C.C_CUSTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION CN ON C.C_NATIONKEY = CN.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION CR ON CN.N_REGIONKEY = CR.R_REGIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART P ON L.L_PARTKEY = P.P_PARTKEY
LEFT JOIN SUPPLYGRAPH_AI.SUPPLY_CHAIN.SYN_PLANTS PL ON PL.PLANT_KEY = MOD(L.L_PARTKEY, 10) + 1;

-- Supplier Performance: Pre-aggregated scorecard
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_SUPPLIER_PERFORMANCE AS
SELECT
    S.S_SUPPKEY AS SUPPLIER_KEY, S.S_NAME AS SUPPLIER_NAME,
    N.N_NAME AS SUPPLIER_NATION, R.R_NAME AS SUPPLIER_REGION,
    COUNT(DISTINCT L.L_ORDERKEY) AS TOTAL_ORDERS,
    COUNT(*) AS TOTAL_LINE_ITEMS,
    SUM(L.L_QUANTITY) AS TOTAL_QUANTITY_SHIPPED,
    ROUND(SUM(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT)), 2) AS TOTAL_REVENUE,
    ROUND(AVG(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT)), 2) AS AVG_LINE_REVENUE,
    SUM(CASE WHEN L.L_RECEIPTDATE <= L.L_COMMITDATE THEN 1 ELSE 0 END) AS ON_TIME_COUNT,
    SUM(CASE WHEN L.L_RECEIPTDATE > L.L_COMMITDATE THEN 1 ELSE 0 END) AS LATE_COUNT,
    ROUND(SUM(CASE WHEN L.L_RECEIPTDATE <= L.L_COMMITDATE THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS ON_TIME_DELIVERY_PCT,
    SUM(CASE WHEN L.L_RETURNFLAG != 'R' THEN 1 ELSE 0 END) AS FULFILLED_COUNT,
    ROUND(SUM(CASE WHEN L.L_RETURNFLAG != 'R' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS FILL_RATE_PCT,
    ROUND(AVG(DATEDIFF('day', O.O_ORDERDATE, L.L_RECEIPTDATE)), 1) AS AVG_DELIVERY_LEAD_TIME_DAYS,
    ROUND(AVG(DATEDIFF('day', L.L_SHIPDATE, L.L_RECEIPTDATE)), 1) AS AVG_SHIPPING_LEAD_TIME_DAYS,
    ROUND(AVG(DATEDIFF('day', O.O_ORDERDATE, L.L_SHIPDATE)), 1) AS AVG_PROCESSING_TIME_DAYS,
    ROUND(AVG(GREATEST(DATEDIFF('day', L.L_COMMITDATE, L.L_RECEIPTDATE), 0)), 1) AS AVG_DAYS_LATE,
    SUM(CASE WHEN L.L_RETURNFLAG = 'R' THEN 1 ELSE 0 END) AS RETURN_COUNT,
    ROUND(SUM(CASE WHEN L.L_RETURNFLAG = 'R' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS RETURN_RATE_PCT,
    ROUND(
        (SUM(CASE WHEN L.L_RECEIPTDATE <= L.L_COMMITDATE THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)) * 0.40
      + (SUM(CASE WHEN L.L_RETURNFLAG != 'R' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)) * 0.35
      + (100 - SUM(CASE WHEN L.L_RETURNFLAG = 'R' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)) * 0.25
    , 2) AS SUPPLIER_PERFORMANCE_SCORE,
    COUNT(DISTINCT L.L_PARTKEY) AS DISTINCT_PARTS_SUPPLIED,
    COUNT(DISTINCT O.O_CUSTKEY) AS DISTINCT_CUSTOMERS_SERVED
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER S
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R ON N.N_REGIONKEY = R.R_REGIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM L ON S.S_SUPPKEY = L.L_SUPPKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
GROUP BY S.S_SUPPKEY, S.S_NAME, N.N_NAME, R.R_NAME;

-- Part Inventory: Days of Inventory per part (GENUINE TPC-H data; plant attributes SYNTHETIC)
--   AVAILABLE_QUANTITY = SUM(PS_AVAILQTY) across all suppliers of the part
--   DEMAND_DAYS        = calendar days in the order window (MAX - MIN order date + 1)
--   AVG_DAILY_DEMAND   = SUM(L_QUANTITY shipped) / DEMAND_DAYS
--   DAYS_OF_INVENTORY  = AVAILABLE_QUANTITY / AVG_DAILY_DEMAND
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_PART_INVENTORY AS
WITH avail AS (
    SELECT PS_PARTKEY, SUM(PS_AVAILQTY) AS AVAILABLE_QUANTITY, COUNT(*) AS SUPPLIER_COUNT
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP GROUP BY PS_PARTKEY
), demand AS (
    SELECT L_PARTKEY, SUM(L_QUANTITY) AS QUANTITY_SHIPPED
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM GROUP BY L_PARTKEY
), demand_window AS (
    SELECT DATEDIFF('day', MIN(O_ORDERDATE), MAX(O_ORDERDATE)) + 1 AS DEMAND_DAYS
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
)
SELECT
    P.P_PARTKEY AS PART_KEY, P.P_NAME AS PART_NAME, P.P_BRAND AS BRAND, P.P_TYPE AS PART_TYPE,
    PL.PLANT_KEY, PL.PLANT_NAME, PL.PLANT_REGION,                       -- [SYNTHETIC]
    A.AVAILABLE_QUANTITY, A.SUPPLIER_COUNT,
    COALESCE(D.QUANTITY_SHIPPED, 0) AS QUANTITY_SHIPPED,
    W.DEMAND_DAYS,
    COALESCE(D.QUANTITY_SHIPPED, 0) / W.DEMAND_DAYS AS AVG_DAILY_DEMAND,
    ROUND(A.AVAILABLE_QUANTITY / NULLIF(COALESCE(D.QUANTITY_SHIPPED, 0) / W.DEMAND_DAYS, 0), 1) AS DAYS_OF_INVENTORY
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART P
JOIN avail A ON A.PS_PARTKEY = P.P_PARTKEY
LEFT JOIN demand D ON D.L_PARTKEY = P.P_PARTKEY
CROSS JOIN demand_window W
LEFT JOIN SUPPLYGRAPH_AI.SUPPLY_CHAIN.SYN_PLANTS PL ON PL.PLANT_KEY = MOD(P.P_PARTKEY, 10) + 1;

-- Shipment Landed Cost (TPC-H quantities and supply cost + SYNTHETIC freight and duty tariffs)
--   PURCHASE_COST = QUANTITY * PS_SUPPLYCOST                            (TPC-H)
--   FREIGHT_COST  = QUANTITY * FREIGHT_RATE_PER_UNIT(ship mode, lane)   (SYNTHETIC tariff)
--   DUTY_COST     = PURCHASE_COST * DUTY_RATE(supplier region -> plant region)  (SYNTHETIC tariff)
--   LANDED_COST   = PURCHASE_COST + FREIGHT_COST + DUTY_COST
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_SHIPMENT_LANDED_COST AS
SELECT
    L.L_ORDERKEY AS ORDER_KEY, L.L_LINENUMBER AS LINE_NUMBER,
    L.L_PARTKEY AS PART_KEY, L.L_SUPPKEY AS SUPPLIER_KEY,
    PL.PLANT_KEY, PL.PLANT_NAME, PL.PLANT_REGION,
    SR.R_NAME AS SUPPLIER_REGION, L.L_SHIPMODE AS SHIP_MODE,
    YEAR(O.O_ORDERDATE) AS ORDER_YEAR,
    IFF(SR.R_NAME = PL.PLANT_REGION, 'DOMESTIC', 'CROSS_REGION') AS LANE_TYPE,
    L.L_QUANTITY AS QUANTITY,
    PS.PS_SUPPLYCOST AS UNIT_SUPPLY_COST,
    FR.FREIGHT_RATE_PER_UNIT,
    DR.DUTY_RATE,
    ROUND(L.L_QUANTITY * PS.PS_SUPPLYCOST, 2) AS PURCHASE_COST,
    ROUND(L.L_QUANTITY * FR.FREIGHT_RATE_PER_UNIT, 2) AS FREIGHT_COST,
    ROUND(L.L_QUANTITY * PS.PS_SUPPLYCOST * DR.DUTY_RATE, 2) AS DUTY_COST,
    ROUND(L.L_QUANTITY * PS.PS_SUPPLYCOST, 2)
      + ROUND(L.L_QUANTITY * FR.FREIGHT_RATE_PER_UNIT, 2)
      + ROUND(L.L_QUANTITY * PS.PS_SUPPLYCOST * DR.DUTY_RATE, 2) AS LANDED_COST
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM L
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS O ON L.L_ORDERKEY = O.O_ORDERKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP PS ON PS.PS_PARTKEY = L.L_PARTKEY AND PS.PS_SUPPKEY = L.L_SUPPKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER S ON L.L_SUPPKEY = S.S_SUPPKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION SN ON S.S_NATIONKEY = SN.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION SR ON SN.N_REGIONKEY = SR.R_REGIONKEY
JOIN SUPPLYGRAPH_AI.SUPPLY_CHAIN.SYN_PLANTS PL ON PL.PLANT_KEY = MOD(L.L_PARTKEY, 10) + 1
JOIN SUPPLYGRAPH_AI.SUPPLY_CHAIN.SYN_FREIGHT_RATES FR
  ON FR.SHIP_MODE = L.L_SHIPMODE AND FR.LANE_TYPE = IFF(SR.R_NAME = PL.PLANT_REGION, 'DOMESTIC', 'CROSS_REGION')
JOIN SUPPLYGRAPH_AI.SUPPLY_CHAIN.SYN_DUTY_RATES DR
  ON DR.ORIGIN_REGION = SR.R_NAME AND DR.DESTINATION_REGION = PL.PLANT_REGION;

-- Metric Definition Comparison: the same metric computed with each source system's definition
-- (definitions from SOURCE_SYSTEM_DEFINITIONS; values computed live from original TPC-H LINEITEM).
CREATE OR REPLACE VIEW SUPPLYGRAPH_AI.SUPPLY_CHAIN.V_METRIC_DEFINITION_COMPARISON AS
WITH v AS (
    SELECT
        AVG(IFF(L_SHIPDATE <= L_COMMITDATE, 1, 0)) * 100                                AS OTD_ERP,
        AVG(IFF(L_RECEIPTDATE <= DATEADD('day', 2, L_COMMITDATE), 1, 0)) * 100          AS OTD_LOGISTICS_TMS,
        AVG(IFF(DATEDIFF('day', L_SHIPDATE, L_RECEIPTDATE) <= 30, 1, 0)) * 100          AS OTD_SUPPLIER_PORTAL,
        AVG(IFF(L_RECEIPTDATE <= L_COMMITDATE, 1, 0)) * 100                             AS OTD_GOVERNED,
        AVG(IFF(L_LINESTATUS = 'F', 1, 0)) * 100                                        AS FILL_ERP,
        SUM(IFF(L_RETURNFLAG <> 'R', L_QUANTITY, 0)) / SUM(L_QUANTITY) * 100            AS FILL_SUPPLIER_PORTAL,
        (1 - AVG(IFF(L_RETURNFLAG = 'R', 1, 0))) * 100                                  AS FILL_GOVERNED,
        SUM(L_EXTENDEDPRICE)                                                            AS SPEND_ERP,
        SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT) * (1 + L_TAX))                           AS SPEND_LOGISTICS_TMS,
        SUM(ROUND(L_EXTENDEDPRICE * (1 - L_DISCOUNT), 2))                               AS SPEND_GOVERNED
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
), vals AS (
    SELECT 'On-Time Delivery' AS METRIC_NAME, 'ERP' AS SOURCE_SYSTEM, OTD_ERP AS METRIC_VALUE, OTD_GOVERNED AS GOVERNED_VALUE FROM v
    UNION ALL SELECT 'On-Time Delivery', 'LOGISTICS_TMS', OTD_LOGISTICS_TMS, OTD_GOVERNED FROM v
    UNION ALL SELECT 'On-Time Delivery', 'SUPPLIER_PORTAL', OTD_SUPPLIER_PORTAL, OTD_GOVERNED FROM v
    UNION ALL SELECT 'On-Time Delivery', 'GOVERNED', OTD_GOVERNED, OTD_GOVERNED FROM v
    UNION ALL SELECT 'Fill Rate', 'ERP', FILL_ERP, FILL_GOVERNED FROM v
    UNION ALL SELECT 'Fill Rate', 'SUPPLIER_PORTAL', FILL_SUPPLIER_PORTAL, FILL_GOVERNED FROM v
    UNION ALL SELECT 'Fill Rate', 'GOVERNED', FILL_GOVERNED, FILL_GOVERNED FROM v
    UNION ALL SELECT 'Total Spend', 'ERP', SPEND_ERP, SPEND_GOVERNED FROM v
    UNION ALL SELECT 'Total Spend', 'LOGISTICS_TMS', SPEND_LOGISTICS_TMS, SPEND_GOVERNED FROM v
    UNION ALL SELECT 'Total Spend', 'GOVERNED', SPEND_GOVERNED, SPEND_GOVERNED FROM v
)
SELECT
    D.METRIC_NAME, D.SOURCE_SYSTEM, D.DEFINITION_TEXT, D.SQL_EXPRESSION, D.IS_GOVERNED,
    ROUND(V.METRIC_VALUE, 4) AS METRIC_VALUE,
    ROUND(V.GOVERNED_VALUE, 4) AS GOVERNED_VALUE,
    ROUND(V.METRIC_VALUE - V.GOVERNED_VALUE, 4) AS VARIANCE_FROM_GOVERNED,
    ROUND((V.METRIC_VALUE - V.GOVERNED_VALUE) / NULLIF(V.GOVERNED_VALUE, 0) * 100, 2) AS VARIANCE_PCT
FROM SUPPLYGRAPH_AI.SUPPLY_CHAIN.SOURCE_SYSTEM_DEFINITIONS D
JOIN vals V ON V.METRIC_NAME = D.METRIC_NAME AND V.SOURCE_SYSTEM = D.SOURCE_SYSTEM;
